name: Ouverture du restaurant

on:
  push:
    branches: [main]

jobs:
  ouverture:
    runs-on: ubuntu-latest
    steps:
      - name: Annoncer l'ouverture
        run: echo "Le restaurant est ouvert !"